# Generated by Django 5.2.7 on 2025-10-08 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('conta', models.CharField(max_length=10, unique=True)),
                ('saldo', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('telefone', models.CharField(max_length=15)),
            ],
        ),
    ]
